// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7eA2oTUiShhed4X1LcPPaU_5hgLJYI0E',
    appId: '1:118089036144:web:aa3b64b9b17df34ad31fb5',
    messagingSenderId: '118089036144',
    projectId: 'split-chat-007',
    authDomain: 'split-chat-007.firebaseapp.com',
    storageBucket: 'split-chat-007.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCu0mHFy9q6slPuv8sVoV8hG91XV4SXYi8',
    appId: '1:118089036144:android:c3b59a670316a68ad31fb5',
    messagingSenderId: '118089036144',
    projectId: 'split-chat-007',
    storageBucket: 'split-chat-007.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgbU7sZU8Y68o4HuGv-WgrD5HNgufzRsA',
    appId: '1:118089036144:ios:a96b7aa2745adeaed31fb5',
    messagingSenderId: '118089036144',
    projectId: 'split-chat-007',
    storageBucket: 'split-chat-007.firebasestorage.app',
    iosBundleId: 'com.example.splitChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgbU7sZU8Y68o4HuGv-WgrD5HNgufzRsA',
    appId: '1:118089036144:ios:a96b7aa2745adeaed31fb5',
    messagingSenderId: '118089036144',
    projectId: 'split-chat-007',
    storageBucket: 'split-chat-007.firebasestorage.app',
    iosBundleId: 'com.example.splitChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7eA2oTUiShhed4X1LcPPaU_5hgLJYI0E',
    appId: '1:118089036144:web:be913911415fc85ed31fb5',
    messagingSenderId: '118089036144',
    projectId: 'split-chat-007',
    authDomain: 'split-chat-007.firebaseapp.com',
    storageBucket: 'split-chat-007.firebasestorage.app',
  );
}
